language: node_js

sudo: false
dist: trusty

node_js:
  - '8'
  - '9'
  - '10'

branches:
  only:
  - master
  - starter-kit
  - demo

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm install

install:
  - travis_retry npm i

before_script:

script:
  - cd back_end
#  - gulp
  - node app.js
#  - 

git:
  depth: 1
